#!/usr/bin/env node
/**
 * project-init.js
 *
 * SessionStart hook (sync): on first launch in a git repo root, scaffold
 * the project structure ohmyclaude expects. Idempotent — subsequent
 * sessions hit the sentinel and exit 0 without touching the filesystem.
 *
 * Creates under <gitroot>:
 *   .claude/ohmyclaude/.initialised   ← sentinel (written LAST)
 *   .claude/usage/                    ← used by usage-tracker.js
 *   .claude/backlog/issues/           ← used by backlog-tracker.js
 *   BACKLOG.md                        ← index stub (only if missing)
 *   CLAUDE.md                         ← starter rules (only if missing)
 *
 * Six guardrails — ALL must pass, else silent no-op:
 *   1. source === 'startup' (skip resume/clear/compact)
 *   2. git root is not $HOME
 *   3. cwd is inside a git repo
 *   4. cwd IS the git root (not a subfolder)
 *   5. this is not the ohmyclaude plugin repo itself
 *   6. sentinel does not already exist
 *
 * Output:
 *   - stdout: pass stdin through (project hook convention)
 *   - stderr: one-line banner on successful first-run init; silent otherwise
 *   - exit: always 0
 */

'use strict';

const fs   = require('fs');
const path = require('path');
const os   = require('os');

function findGitRoot(start) {
  let dir = path.resolve(start);
  while (true) {
    if (fs.existsSync(path.join(dir, '.git'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

function isOhmyclaudeRepo(root) {
  const manifest = path.join(root, '.claude-plugin', 'plugin.json');
  if (!fs.existsSync(manifest)) return false;
  try {
    const pkg = JSON.parse(fs.readFileSync(manifest, 'utf8'));
    return pkg.name === 'ohmyclaude';
  } catch {
    return false;
  }
}

const CLAUDE_MD_TEMPLATE = `# CLAUDE.md

This project uses the **ohmyclaude** plugin — a 10-agent pipeline for structured software delivery.

## Available commands

- \`/forge <goal>\` — run the full 10-agent pipeline (discover → ship)
- \`/save\` — persist session context to \`~/.claude/ohmyclaude/sessions/\`
- \`/load\` — resume a saved session for this directory

## Conventions

- **Backlog**: \`ISS-*.md\` files under \`.claude/backlog/issues/\`. \`BACKLOG.md\` at repo root is auto-maintained by the backlog-tracker hook.
- **Usage telemetry**: per-project metrics live under \`.claude/usage/\` (add to \`.gitignore\` if not already).
- **Session history**: saved under \`~/.claude/ohmyclaude/sessions/\` (user scope, not this repo).

## Rules

- Prefer editing existing files over creating new ones.
- No placeholder values — leave explicit TODO comments if uncertain.
- Commit messages follow Conventional Commits (\`feat:\`, \`fix:\`, \`chore:\`, \`docs:\`, \`refactor:\`, \`test:\`, \`ci:\`).
- Never commit secrets; the \`pre-write-check\` hook will block common patterns, but treat it as defence-in-depth not a guarantee.

_This file was auto-generated by ohmyclaude project-init. Edit freely._
`;

const BACKLOG_TEMPLATE = `# Backlog

Issues are tracked as \`ISS-*.md\` files under \`.claude/backlog/issues/\`.
This index is auto-maintained by the ohmyclaude \`backlog-tracker\` hook.

_No issues yet._
`;

let raw = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', c => raw += c);
process.stdin.on('end', () => {
  process.stdout.write(raw);

  let evt = {};
  try { evt = JSON.parse(raw); } catch {}

  if (evt.source && evt.source !== 'startup') return process.exit(0);

  const cwd = evt.cwd || process.cwd();
  const gitRoot = findGitRoot(cwd);
  if (!gitRoot) return process.exit(0);
  if (path.resolve(cwd) !== gitRoot) return process.exit(0);
  if (gitRoot === os.homedir()) return process.exit(0);
  if (isOhmyclaudeRepo(gitRoot)) return process.exit(0);

  const sentinel = path.join(gitRoot, '.claude', 'ohmyclaude', '.initialised');
  if (fs.existsSync(sentinel)) return process.exit(0);

  const created = [];
  try {
    fs.mkdirSync(path.join(gitRoot, '.claude', 'ohmyclaude'), { recursive: true });
    created.push('.claude/ohmyclaude/');

    fs.mkdirSync(path.join(gitRoot, '.claude', 'usage'), { recursive: true });
    created.push('.claude/usage/');

    fs.mkdirSync(path.join(gitRoot, '.claude', 'backlog', 'issues'), { recursive: true });
    created.push('.claude/backlog/issues/');

    const backlogPath = path.join(gitRoot, 'BACKLOG.md');
    if (!fs.existsSync(backlogPath)) {
      fs.writeFileSync(backlogPath, BACKLOG_TEMPLATE);
      created.push('BACKLOG.md');
    }

    const claudeMdPath = path.join(gitRoot, 'CLAUDE.md');
    if (!fs.existsSync(claudeMdPath)) {
      fs.writeFileSync(claudeMdPath, CLAUDE_MD_TEMPLATE);
      created.push('CLAUDE.md');
    }

    fs.writeFileSync(sentinel, JSON.stringify({
      version: 1,
      initialised_at: new Date().toISOString(),
      created
    }, null, 2) + '\n');
  } catch {
    return process.exit(0);
  }

  process.stderr.write(
    `[ohmyclaude] Initialised project at ${gitRoot}: ${created.join(', ')}\n`
  );
  process.exit(0);
});
